--设置component
AddLocaleLang({
	CollectiveTask_0=[[世家资源:]];
	CollectiveTask_1=[[经验:]];
	CollectiveTask_2=[[银两:]];
	CollectiveTask_3=[[贡献:]];
	CollectiveTask_4=[[五行真气:]];
	CollectiveTask_5=[[（全部完成后可获得以下奖励）]];
});
