--设置component
AddLocaleLang({
	DailyPoint_0=[[慕容雪]];
	DailyPoint_1=[[活动NPC：]];
	DailyPoint_2=[[正在进行活动：]];
	DailyPoint_3=[[活动简介：]];
	DailyPoint_4=[[经验：]];
	DailyPoint_5=[[银两：]];
	DailyPoint_6=[[装备：]];
	DailyPoint_7=[[立即前往]];
	DailyPoint_8=[[查看活动]];
	DailyPoint_9=[[活动奖励:]];
});
