--设置component
AddLocaleLang({
	fuben_zhujiemian_0=[[关]];
	fuben_zhujiemian_1=[[进入副本]];
	fuben_zhujiemian_2=[[开创副本]];
	fuben_zhujiemian_3=[[催队长快来]];
	fuben_zhujiemian_4=[[当您掉线或其他原因离开副本时，您有3分钟的时间返回副本，否则将视为放弃副本。]];
	fuben_zhujiemian_5=[[小有成就]];
	fuben_zhujiemian_6=[[大起大落]];
	fuben_zhujiemian_7=[[拥有元宝]];
});
