--设置component
AddLocaleLang({
	GodHorseUp_0=[[关]];
	GodHorseUp_1=[[遣散]];
	GodHorseUp_2=[[开始升阶]];
	GodHorseUp_3=[[自动升阶]];
	GodHorseUp_4=[[消耗材料：]];
	GodHorseUp_5=[[消耗银两：]];
	GodHorseUp_6=[[本次操作使用]];
	GodHorseUp_7=[[本次操作使用]];
	GodHorseUp_8=[[自动购买所需材料]];
	GodHorseUp_9=[[优先使用非绑定材料]];
	GodHorseUp_10=[[元宝：]];
	GodHorseUp_11=[[消耗材料]];
	GodHorseUp_12=[[关]];
	GodHorseUp_13=[[礼金：]];
	GodHorseUp_14=[[2倍]];
	GodHorseUp_15=[[2倍]];
	GodHorseUp_16=[[消耗元宝：]];
	GodHorseUp_17=[[拥有元宝]];
	GodHorseUp_18=[[天官赐福]];
	GodHorseUp_19=[[天官赐福值越高，升阶越容易]];
});
