--设置component
AddLocaleLang({
	HDYeWaiBOSS_0=[[BOSS有机会掉落以下物品:]];
	HDYeWaiBOSS_1=[[BOSS简介]];
	HDYeWaiBOSS_2=[[BOSS简介]];
	HDYeWaiBOSS_3=[[野外BOSS名称]];
	HDYeWaiBOSS_4=[[等级]];
	HDYeWaiBOSS_5=[[BOOS有机会掉落以下物品:]];
	HDYeWaiBOSS_6=[[击杀者：]];
	HDYeWaiBOSS_7=[[前往]];
	HDYeWaiBOSS_8=[[所在地图：]];
	HDYeWaiBOSS_9=[[襄阳野郊（秘境）]];
	HDYeWaiBOSS_10=[[八小时五分后刷新]];
	HDYeWaiBOSS_11=[[击杀者：]];
	HDYeWaiBOSS_12=[[[999区]王康兴王康兴]];
	HDYeWaiBOSS_13=[[私聊]];
	HDYeWaiBOSS_14=[[查看]];
	HDYeWaiBOSS_15=[[交友]];
	HDYeWaiBOSS_16=[[交易]];
	HDYeWaiBOSS_17=[[组队]];
	HDYeWaiBOSS_18=[[世家邀请]];
	HDYeWaiBOSS_19=[[看摊]];
	HDYeWaiBOSS_20=[[求婚]];
	HDYeWaiBOSS_21=[[成就对比]];
	HDYeWaiBOSS_22=[[双修]];
});
