--设置component
AddLocaleLang({
	MainPageFunBtn_0=[[石]];
	MainPageFunBtn_1=[[附]];
	MainPageFunBtn_2=[[炼]];
	MainPageFunBtn_3=[[甲]];
	MainPageFunBtn_4=[[坐骑]];
	MainPageFunBtn_5=[[帮会]];
	MainPageFunBtn_6=[[设置]];
	MainPageFunBtn_7=[[挂机]];
	MainPageFunBtn_8=[[任务]];
	MainPageFunBtn_9=[[五行]];
	MainPageFunBtn_10=[[经脉]];
	MainPageFunBtn_11=[[武功]];
	MainPageFunBtn_12=[[包裹]];
	MainPageFunBtn_13=[[人物]];
	MainPageFunBtn_14=[[队伍]];
	MainPageFunBtn_15=[[好友]];
	MainPageFunBtn_16=[[好友]];
});
