--设置component
AddLocaleLang({
	QiangHuaMain_0=[[开始强化]];
	QiangHuaMain_1=[[自动强化]];
	QiangHuaMain_2=[[本次操作使用]];
	QiangHuaMain_3=[[神龙果]];
	QiangHuaMain_4=[[本次操作使用]];
	QiangHuaMain_5=[[(可提升强化成功率)]];
	QiangHuaMain_6=[[成功率：]];
	QiangHuaMain_7=[[一般]];
	QiangHuaMain_8=[[消耗材料:]];
	QiangHuaMain_9=[[神龙果]];
	QiangHuaMain_10=[[消耗银两：]];
	QiangHuaMain_11=[[为我自动强化至]];
	QiangHuaMain_12=[[VIP特权(开通VIP自动强化)]];
	QiangHuaMain_13=[[摆摊]];
});
