--设置component
AddLocaleLang({
	ShuZhiMain_0=[[开始洗炼]];
	ShuZhiMain_1=[[自动洗炼]];
	ShuZhiMain_2=[[本次操作使用]];
	ShuZhiMain_3=[[个幸运珠]];
	ShuZhiMain_4=[[本次操作使用]];
	ShuZhiMain_5=[[(可提升强化成功率)]];
	ShuZhiMain_6=[[成功率：]];
	ShuZhiMain_7=[[一般]];
	ShuZhiMain_8=[[消耗材料:]];
	ShuZhiMain_9=[[神龙果]];
	ShuZhiMain_10=[[消耗材料:]];
	ShuZhiMain_11=[[摆摊]];
	ShuZhiMain_12=[[为我自动洗炼至极致附加属性]];
	ShuZhiMain_13=[[VIP特权(开通VIP自动洗炼)]];
});
