--设置component
AddLocaleLang({
	TaskMain_0=[[正传]];
	TaskMain_1=[[外传]];
	TaskMain_2=[[风云]];
	TaskMain_3=[[追 踪]];
	TaskMain_4=[[已接任务]];
	TaskMain_5=[[可接任务]];
	TaskMain_6=[[主线]];
	TaskMain_7=[[主线]];
	TaskMain_8=[[主线]];
	TaskMain_9=[[主线]];
	TaskMain_10=[[主线]];
	TaskMain_11=[[主线]];
	TaskMain_12=[[主线]];
	TaskMain_13=[[每8环可获如下额外奖励：]];
	TaskMain_14=[[注：每日可接20环风云任务。]];
	TaskMain_15=[[确定]];
	TaskMain_16=[[一键完成本环]];
});
