--设置component
AddLocaleLang({
	team_zhanyou_0=[[一键添加]];
	team_zhanyou_1=[[他们是与你一同奋战的战友]];
	team_zhanyou_2=[[摆摊]];
	team_zhanyou_3=[[私聊]];
	team_zhanyou_4=[[查看]];
	team_zhanyou_5=[[交友]];
	team_zhanyou_6=[[交易]];
	team_zhanyou_7=[[世家邀请]];
	team_zhanyou_8=[[看摊]];
	team_zhanyou_9=[[团练]];
	team_zhanyou_10=[[加入世家]];
	team_zhanyou_11=[[成就对比]];
	team_zhanyou_12=[[求婚]];
	team_zhanyou_13=[[张逸尘]];
	team_zhanyou_14=[[加为好友]];
});
