--设置component
AddLocaleLang({
	youjian_0=[[摆摊]];
	youjian_1=[[全部]];
	youjian_2=[[未读]];
	youjian_3=[[已读]];
	youjian_4=[[上一封]];
	youjian_5=[[下一封]];
	youjian_6=[[扩展（发送）]];
	youjian_7=[[返 回]];
	youjian_8=[[领 取]];
	youjian_9=[[发件人:]];
	youjian_10=[[主  题:]];
	youjian_11=[[发件日期:]];
	youjian_12=[[]];
	youjian_13=[[到期时间:]];
	youjian_14=[[删 除]];
	youjian_15=[[发件人]];
	youjian_16=[[主题]];
	youjian_17=[[发件日期]];
	youjian_18=[[删 除]];
	youjian_19=[[取消标记]];
	youjian_20=[[删除已读]];
	youjian_21=[[全部标记]];
	youjian_22=[[数量：]];
	youjian_23=[[上一页]];
	youjian_24=[[下一页]];
	youjian_25=[[摆摊]];
	youjian_26=[[摆摊]];
	youjian_27=[[摆摊]];
	youjian_28=[[摆摊]];
	youjian_29=[[摆摊]];
	youjian_30=[[摆摊]];
	youjian_31=[[摆摊]];
	youjian_32=[[摆摊]];
	youjian_33=[[摆摊]];
	youjian_34=[[摆摊]];
});
