dofile '../Config/SkillConfig/SkillBufConfig.lua'
dofile '../Config/SkillConfig/SkillConfig.lua'
dofile '../Config/SkillConfig/SkillStudyConfig.lua'
dofile '../Config/SkillConfig/SkillStringConfig.lua'
dofile '../Config/SkillConfig/SkillScript.lua'
dofile '../Config/SkillConfig/SkillAction.lua'
dofile '../Config/SkillConfig/MonsterSkillScript.lua'
dofile '../Config/SkillConfig/SkillLoginConfig.lua'
dofile '../Config/SkillConfig/TaskMonsterSkillScript.lua'
dofile '../Config/SkillConfig/CopyMonsterSkillScript.lua'
dofile '../Config/SkillConfig/ActivityMonsterSkillScript.lua'
dofile '../Config/SkillConfig/SkillSwordScript.lua'
dofile '../Config/SkillConfig/SkillEventConfig.lua'
dofile '../Config/SkillConfig/MoodIndex.lua'
dofile '../Config/SkillConfig/SkillTitleConfig.lua'
dofile '../Config/SkillConfig/SkillUIConfig.lua'
dofile '../Config/SkillConfig/Silent.lua'
dofile '../Config/SkillConfig/PetSkillConfig.lua'
dofile '../Config/SkillConfig/PetPassivitySkillConfig.lua'


