--[[
:序号
id:ID
name:名称:类型说明
des:描述
limit_item:装备限制:作者:
0 不需要装备武器
1 需要装备武器
2需要装备暗器

skill_type:技能类型:0：主动攻击技能;
1：主动增益技能;
2：被动触发技能;
3：被动永久生效技能;
4：主动减益技能;
5：影响技能;
6：等级附加技能（攻击）；
is_hit:是否必中:作者:
0:否
1:必中
Initial_proc:初始触发几率
range_type:目标类型:作者:

0 单体敌人
1 单体友人
2 自己
3 目标范围敌人
4 目标范围友人（包括自己）
5 自身范围敌人
6 自身范围友人（包括自己）

range:影响范围:作者:
设定范围技能的范围大小
distance:释放距离
sing_time:读条时间
cool_delay:冷却时间
consumption_mp:使用消耗MP
consumption_item:使用消耗物品
consumption_num:消耗数量
need_lv:学习等级
need_book:学习书籍
book_des:书籍来源描述
properties_add:提升属性类型:此处填变量名

init_value:初始数值:0：直接操作玩家属性
其他：操作此数值后加到玩家属性
value_add:升级提升数值:若初始数值不为0则影响初始数值，否则影响人物身上的实际值

percentage_add:升级提升百分比:若初始数值不为0则影响初始数值，否则影响人物身上的实际值


effect:触发效果:触发buff_id

probability_add:升级提升触发几率
restraint_skill:克制技能id
value_less:升级减少数值
percentage_less:升级减少数值百分比
probability_less:升级减少触发几率
fear_skill:受此id的技能克制
skill_add:附加技能
skill_percentage_add:升级提升触发几率
icon:已学习图标
gray_icon:未学习图标
atk_mov_id1:攻击方动作id
def_mov_id:受击方动作id
par_id:光效ID
skill_kinds:技能种类
skill_target:目标类型
range_x:影响范围X
range_y:影响范围Y
skill_damagetimer:伤害延迟计算
skill_auto:是否自动攻击
--]]
_G.gbl_data_skill={ 
[1]={id=1,name='普通攻击',des='江湖杂学，习以筑基。对目标造成基础（100%）的伤害。',limit_item=0,skill_type=1,is_hit=0,Initial_proc=0,range_type=0,range=0,distance=3,sing_time=0,cool_delay=1000,consumption_mp=1,consumption_item=0,consumption_num=0,need_lv=0,need_book=0,book_des='0',properties_add='attack',init_value=0,value_add=0,percentage_add=0,effect=0,probability_add=0,restraint_skill=0,value_less=0,percentage_less=0,probability_less=0,fear_skill=0,skill_add=0,skill_percentage_add=0,icon='pugong.png',gray_icon='pugong.png',atk_mov_id1=12,def_mov_id=21,par_id=1,skill_kinds=0,skill_target=100,range_x=5,range_y=5,skill_damagetimer=3,skill_auto=1,},
[2]={id=2,name='远程技能',des='远程技能',limit_item=0,skill_type=1,is_hit=0,Initial_proc=0,range_type=0,range=0,distance=15,sing_time=0,cool_delay=1000,consumption_mp=1,consumption_item=0,consumption_num=0,need_lv=0,need_book=0,book_des='0',properties_add='attack',init_value=0,value_add=0,percentage_add=0,effect=0,probability_add=0,restraint_skill=0,value_less=0,percentage_less=0,probability_less=0,fear_skill=0,skill_add=0,skill_percentage_add=0,icon='gun_jineng.png',gray_icon='gun_jineng_disable.png',atk_mov_id1=12,def_mov_id=21,par_id=2,skill_kinds=0,skill_target=100,range_x=10,range_y=5,skill_damagetimer=3,skill_auto=1,},
[3]={id=3,name='怪物普攻',des='怪物普攻',limit_item=0,skill_type=1,is_hit=0,Initial_proc=0,range_type=0,range=0,distance=3,sing_time=0,cool_delay=1000,consumption_mp=1,consumption_item=0,consumption_num=0,need_lv=0,need_book=0,book_des='0',properties_add='attack',init_value=0,value_add=0,percentage_add=0,effect=0,probability_add=0,restraint_skill=0,value_less=0,percentage_less=0,probability_less=0,fear_skill=0,skill_add=0,skill_percentage_add=0,icon='shu.png',gray_icon='0',atk_mov_id1=12,def_mov_id=0,par_id=3,skill_kinds=0,skill_target=100,range_x=10,range_y=5,skill_damagetimer=3,skill_auto=1,},
[11001]={id=11001,name='五毒掌',des='给目标附加一个buff 2秒持续扣血',limit_item=0,skill_type=1,is_hit=1,Initial_proc=0,range_type=0,range=0,distance=5,sing_time=0,cool_delay=1000,consumption_mp=1,consumption_item=0,consumption_num=0,need_lv=0,need_book=0,book_des='0',properties_add='attack',init_value=0,value_add=0,percentage_add=0,effect=0,probability_add=0,restraint_skill=0,value_less=0,percentage_less=0,probability_less=0,fear_skill=0,skill_add=0,skill_percentage_add=0,icon='JX_JiuYin.png',gray_icon='JX_JiuYinDisable.png',atk_mov_id1=12,def_mov_id=21,par_id=60002,skill_kinds=0,skill_target=100,range_x=0,range_y=0,skill_damagetimer=0,skill_auto=0,},
[11002]={id=11002,name='五气朝元',des='每3秒持续给回复2%的血，持续30秒！',limit_item=0,skill_type=1,is_hit=1,Initial_proc=0,range_type=0,range=0,distance=20,sing_time=0,cool_delay=1000,consumption_mp=1,consumption_item=0,consumption_num=0,need_lv=0,need_book=0,book_des='0',properties_add='attack',init_value=0,value_add=0,percentage_add=2,effect=0,probability_add=0,restraint_skill=0,value_less=0,percentage_less=0,probability_less=0,fear_skill=0,skill_add=0,skill_percentage_add=0,icon='JX_WuJi.png',gray_icon='JX_WuJiDisable.png',atk_mov_id1=12,def_mov_id=0,par_id=0,skill_kinds=0,skill_target=1,range_x=0,range_y=0,skill_damagetimer=3,skill_auto=0,},
[12001]={id=12001,name='剑内功1',des='剑内功1',limit_item=0,skill_type=100,is_hit=0,Initial_proc=0,range_type=0,range=0,distance=0,sing_time=0,cool_delay=1000,consumption_mp=1,consumption_item=0,consumption_num=0,need_lv=0,need_book=0,book_des='0',properties_add='attack',init_value=0,value_add=0,percentage_add=2,effect=0,probability_add=0,restraint_skill=0,value_less=0,percentage_less=0,probability_less=0,fear_skill=0,skill_add=0,skill_percentage_add=0,icon='JX_ChongXuYangQi.png',gray_icon='JX_ChongXuYangQiDisable.png',atk_mov_id1=12,def_mov_id=0,par_id=5011,skill_kinds=1,skill_target=0,range_x=0,range_y=0,skill_damagetimer=3,skill_auto=0,},
[12002]={id=12002,name='剑内功2',des='剑内功2',limit_item=0,skill_type=100,is_hit=0,Initial_proc=0,range_type=0,range=0,distance=0,sing_time=0,cool_delay=1000,consumption_mp=1,consumption_item=0,consumption_num=0,need_lv=0,need_book=0,book_des='0',properties_add='attack',init_value=0,value_add=0,percentage_add=2,effect=0,probability_add=0,restraint_skill=0,value_less=0,percentage_less=0,probability_less=0,fear_skill=0,skill_add=0,skill_percentage_add=0,icon='JX_PuZhao.png',gray_icon='JX_PuZhaoDisable.png',atk_mov_id1=12,def_mov_id=0,par_id=5012,skill_kinds=1,skill_target=0,range_x=0,range_y=0,skill_damagetimer=3,skill_auto=0,},
[13001]={id=13001,name='青莲秘箓',des='血量上限增加（技能等级*14）',limit_item=0,skill_type=10,is_hit=0,Initial_proc=0,range_type=0,range=0,distance=0,sing_time=0,cool_delay=1000,consumption_mp=1,consumption_item=0,consumption_num=0,need_lv=0,need_book=0,book_des='0',properties_add='attack',init_value=0,value_add=0,percentage_add=2,effect=0,probability_add=0,restraint_skill=0,value_less=0,percentage_less=0,probability_less=0,fear_skill=0,skill_add=0,skill_percentage_add=0,icon='Icon_sk_13001_1.png',gray_icon='Icon_sk_13001_0.png',atk_mov_id1=12,def_mov_id=0,par_id=0,skill_kinds=2,skill_target=0,range_x=0,range_y=0,skill_damagetimer=3,skill_auto=0,},
[13002]={id=13002,name='天元心法',des='内力上限增加（技能等级*8）',limit_item=0,skill_type=10,is_hit=0,Initial_proc=0,range_type=0,range=0,distance=0,sing_time=0,cool_delay=1000,consumption_mp=1,consumption_item=0,consumption_num=0,need_lv=0,need_book=0,book_des='0',properties_add='attack',init_value=0,value_add=0,percentage_add=2,effect=0,probability_add=0,restraint_skill=0,value_less=0,percentage_less=0,probability_less=0,fear_skill=0,skill_add=0,skill_percentage_add=0,icon='Icon_sk_13002_1.png',gray_icon='Icon_sk_13002_0.png',atk_mov_id1=12,def_mov_id=0,par_id=0,skill_kinds=2,skill_target=0,range_x=0,range_y=0,skill_damagetimer=3,skill_auto=0,},
[13003]={id=13003,name='龙象般若功',des='防御力增加（技能等级*3）',limit_item=0,skill_type=10,is_hit=0,Initial_proc=0,range_type=0,range=0,distance=0,sing_time=0,cool_delay=1000,consumption_mp=1,consumption_item=0,consumption_num=0,need_lv=0,need_book=0,book_des='0',properties_add='attack',init_value=0,value_add=0,percentage_add=2,effect=0,probability_add=0,restraint_skill=0,value_less=0,percentage_less=0,probability_less=0,fear_skill=0,skill_add=0,skill_percentage_add=0,icon='Icon_sk_13003_1.png',gray_icon='Icon_sk_13003_0.png',atk_mov_id1=12,def_mov_id=0,par_id=0,skill_kinds=2,skill_target=0,range_x=0,range_y=0,skill_damagetimer=3,skill_auto=0,},
[13004]={id=13004,name='玄功要诀',des='攻击增加（技能等级*5）',limit_item=0,skill_type=10,is_hit=0,Initial_proc=0,range_type=0,range=0,distance=0,sing_time=0,cool_delay=1000,consumption_mp=1,consumption_item=0,consumption_num=0,need_lv=0,need_book=0,book_des='0',properties_add='attack',init_value=0,value_add=0,percentage_add=2,effect=0,probability_add=0,restraint_skill=0,value_less=0,percentage_less=0,probability_less=0,fear_skill=0,skill_add=0,skill_percentage_add=0,icon='Icon_sk_13004_1.png',gray_icon='Icon_sk_13004_0.png',atk_mov_id1=12,def_mov_id=0,par_id=0,skill_kinds=2,skill_target=0,range_x=0,range_y=0,skill_damagetimer=3,skill_auto=0,},
[13005]={id=13005,name='云龙三折',des='闪避增加（技能等级*5）',limit_item=0,skill_type=10,is_hit=0,Initial_proc=0,range_type=0,range=0,distance=0,sing_time=0,cool_delay=1000,consumption_mp=1,consumption_item=0,consumption_num=0,need_lv=0,need_book=0,book_des='0',properties_add='attack',init_value=0,value_add=0,percentage_add=2,effect=0,probability_add=0,restraint_skill=0,value_less=0,percentage_less=0,probability_less=0,fear_skill=0,skill_add=0,skill_percentage_add=0,icon='Icon_sk_13005_1.png',gray_icon='Icon_sk_13005_0.png',atk_mov_id1=12,def_mov_id=0,par_id=0,skill_kinds=2,skill_target=0,range_x=0,range_y=0,skill_damagetimer=3,skill_auto=0,},
[13006]={id=13006,name='天魔解体',des='暴击增加（技能等级*2）',limit_item=0,skill_type=10,is_hit=0,Initial_proc=0,range_type=0,range=0,distance=0,sing_time=0,cool_delay=1000,consumption_mp=1,consumption_item=0,consumption_num=0,need_lv=0,need_book=0,book_des='0',properties_add='attack',init_value=0,value_add=0,percentage_add=2,effect=0,probability_add=0,restraint_skill=0,value_less=0,percentage_less=0,probability_less=0,fear_skill=0,skill_add=0,skill_percentage_add=0,icon='Icon_sk_13006_1.png',gray_icon='Icon_sk_13006_0.png',atk_mov_id1=12,def_mov_id=0,par_id=0,skill_kinds=2,skill_target=0,range_x=0,range_y=0,skill_damagetimer=3,skill_auto=0,},
[14001]={id=14001,name='自断经脉',des='自杀技能',limit_item=0,skill_type=1,is_hit=1,Initial_proc=0,range_type=0,range=0,distance=20,sing_time=0,cool_delay=1000,consumption_mp=1,consumption_item=0,consumption_num=0,need_lv=0,need_book=0,book_des='0',properties_add='attack',init_value=0,value_add=0,percentage_add=2,effect=0,probability_add=0,restraint_skill=0,value_less=0,percentage_less=0,probability_less=0,fear_skill=0,skill_add=0,skill_percentage_add=0,icon='XF_FanXinJue.png',gray_icon='XF_FanXinJueDisable.png',atk_mov_id1=0,def_mov_id=0,par_id=0,skill_kinds=2,skill_target=1,range_x=0,range_y=0,skill_damagetimer=3,skill_auto=0,},
[15000]={id=15000,name='星火长空',des='周围怪物死光光',limit_item=0,skill_type=1,is_hit=0,Initial_proc=0,range_type=1,range=0,distance=20,sing_time=0,cool_delay=1000,consumption_mp=1,consumption_item=0,consumption_num=0,need_lv=0,need_book=0,book_des='0',properties_add='attack',init_value=0,value_add=0,percentage_add=2,effect=0,probability_add=0,restraint_skill=0,value_less=0,percentage_less=0,probability_less=0,fear_skill=0,skill_add=0,skill_percentage_add=0,icon='JX_PuZhao.png',gray_icon='JX_PuZhaoDisable.png',atk_mov_id1=12,def_mov_id=21,par_id=15000,skill_kinds=0,skill_target=100,range_x=8,range_y=5,skill_damagetimer=3.5,skill_auto=0,},
[21001]={id=21001,name='剑影凝光',des='快剑留影，凝光慑敌。对目标造成基础（100%+技能等级*3）加固定伤害点（技能等级*4）的伤害。',limit_item=1,skill_type=1,is_hit=0,Initial_proc=0,range_type=0,range=0,distance=3,sing_time=0,cool_delay=1000,consumption_mp=1,consumption_item=0,consumption_num=0,need_lv=0,need_book=0,book_des='0',properties_add='attack',init_value=0,value_add=0,percentage_add=2,effect=0,probability_add=0,restraint_skill=0,value_less=0,percentage_less=0,probability_less=0,fear_skill=0,skill_add=0,skill_percentage_add=0,icon='Icon_sk_21001_1.png',gray_icon='Icon_sk_21001_0.png',atk_mov_id1=12,def_mov_id=21,par_id=21001,skill_kinds=0,skill_target=100,range_x=3,range_y=0,skill_damagetimer=2,skill_auto=1,},
[21002]={id=21002,name='剑羽惊寰',des='剑飞如羽，势惊人寰。对目标造成基础（100%+技能等级*2）加固定伤害点（技能等级*3）的伤害。',limit_item=1,skill_type=1,is_hit=0,Initial_proc=0,range_type=0,range=0,distance=10,sing_time=0,cool_delay=1000,consumption_mp=1,consumption_item=0,consumption_num=0,need_lv=0,need_book=0,book_des='0',properties_add='attack',init_value=0,value_add=0,percentage_add=2,effect=0,probability_add=0,restraint_skill=0,value_less=0,percentage_less=0,probability_less=0,fear_skill=0,skill_add=0,skill_percentage_add=0,icon='Icon_sk_21002_1.png',gray_icon='Icon_sk_21002_0.png',atk_mov_id1=12,def_mov_id=21,par_id=21002,skill_kinds=0,skill_target=100,range_x=6,range_y=0,skill_damagetimer=2,skill_auto=1,},
[21004]={id=21004,name='剑雨削香',des='挥剑成雨，削香断玉。对目标造成基础（100%+技能等级*1.5）加固定伤害点（技能等级*2）的伤害。',limit_item=1,skill_type=1,is_hit=0,Initial_proc=0,range_type=1,range=0,distance=4.5,sing_time=0,cool_delay=1000,consumption_mp=1,consumption_item=0,consumption_num=0,need_lv=0,need_book=0,book_des='0',properties_add='attack',init_value=0,value_add=0,percentage_add=2,effect=0,probability_add=0,restraint_skill=0,value_less=0,percentage_less=0,probability_less=0,fear_skill=0,skill_add=0,skill_percentage_add=0,icon='Icon_sk_21004_1.png',gray_icon='Icon_sk_21004_0.png',atk_mov_id1=12,def_mov_id=21,par_id=21004,skill_kinds=0,skill_target=100,range_x=5,range_y=0,skill_damagetimer=4,skill_auto=1,},
[21005]={id=21005,name='剑荡八方',des='剑意雄浑，气荡八方。对目标造成基础（100%+技能等级*1.3）加固定伤害点（技能等级*2）的伤害。',limit_item=1,skill_type=1,is_hit=0,Initial_proc=0,range_type=2,range=0,distance=10,sing_time=0,cool_delay=1000,consumption_mp=1,consumption_item=0,consumption_num=0,need_lv=0,need_book=0,book_des='0',properties_add='attack',init_value=0,value_add=0,percentage_add=2,effect=0,probability_add=0,restraint_skill=0,value_less=0,percentage_less=0,probability_less=0,fear_skill=0,skill_add=0,skill_percentage_add=0,icon='Icon_sk_21005_1.png',gray_icon='Icon_sk_21005_0.png',atk_mov_id1=12,def_mov_id=21,par_id=21005,skill_kinds=0,skill_target=100,range_x=5,range_y=0,skill_damagetimer=2.5,skill_auto=1,},
[31001]={id=31001,name='厉刀裂地',des='刀锋冷厉，碎石裂地。对目标造成基础（100%+技能等级*3）加固定伤害点（技能等级*4）的伤害。',limit_item=1,skill_type=1,is_hit=0,Initial_proc=0,range_type=0,range=0,distance=3,sing_time=0,cool_delay=1000,consumption_mp=1,consumption_item=0,consumption_num=0,need_lv=0,need_book=0,book_des='0',properties_add='attack',init_value=0,value_add=0,percentage_add=2,effect=0,probability_add=0,restraint_skill=0,value_less=0,percentage_less=0,probability_less=0,fear_skill=0,skill_add=0,skill_percentage_add=0,icon='Icon_sk_31001_1.png',gray_icon='Icon_sk_31001_0.png',atk_mov_id1=62,def_mov_id=21,par_id=31001,skill_kinds=0,skill_target=100,range_x=3,range_y=0,skill_damagetimer=2,skill_auto=1,},
[31002]={id=31002,name='狂刀断风',des='狂刀豪舞，断风遏云。对目标造成基础（100%+技能等级*2）加固定伤害点（技能等级*3）的伤害。',limit_item=1,skill_type=1,is_hit=0,Initial_proc=0,range_type=0,range=0,distance=10,sing_time=0,cool_delay=1000,consumption_mp=1,consumption_item=0,consumption_num=0,need_lv=0,need_book=0,book_des='0',properties_add='attack',init_value=0,value_add=0,percentage_add=2,effect=0,probability_add=0,restraint_skill=0,value_less=0,percentage_less=0,probability_less=0,fear_skill=0,skill_add=0,skill_percentage_add=0,icon='Icon_sk_31002_1.png',gray_icon='Icon_sk_31002_0.png',atk_mov_id1=12,def_mov_id=21,par_id=31002,skill_kinds=0,skill_target=100,range_x=6,range_y=0,skill_damagetimer=2,skill_auto=1,},
[31004]={id=31004,name='哀刀回魂',des='战魂未已，哀则必胜。对目标造成基础（100%+技能等级*1.5）加固定伤害点（技能等级*2）的伤害。',limit_item=1,skill_type=1,is_hit=0,Initial_proc=0,range_type=1,range=0,distance=4.5,sing_time=0,cool_delay=1000,consumption_mp=1,consumption_item=0,consumption_num=0,need_lv=0,need_book=0,book_des='0',properties_add='attack',init_value=0,value_add=0,percentage_add=2,effect=0,probability_add=0,restraint_skill=0,value_less=0,percentage_less=0,probability_less=0,fear_skill=0,skill_add=0,skill_percentage_add=0,icon='Icon_sk_31004_1.png',gray_icon='Icon_sk_31004_0.png',atk_mov_id1=12,def_mov_id=21,par_id=31004,skill_kinds=0,skill_target=100,range_x=5,range_y=0,skill_damagetimer=4,skill_auto=1,},
[31005]={id=31005,name='乱刀破军',des='无招之刀，当无可挡。对目标造成基础（100%+技能等级*1.3）加固定伤害点（技能等级*2）的伤害。',limit_item=1,skill_type=1,is_hit=0,Initial_proc=0,range_type=2,range=0,distance=10,sing_time=0,cool_delay=1000,consumption_mp=1,consumption_item=0,consumption_num=0,need_lv=0,need_book=0,book_des='0',properties_add='attack',init_value=0,value_add=0,percentage_add=2,effect=0,probability_add=0,restraint_skill=0,value_less=0,percentage_less=0,probability_less=0,fear_skill=0,skill_add=0,skill_percentage_add=0,icon='Icon_sk_31005_1.png',gray_icon='Icon_sk_31005_0.png',atk_mov_id1=12,def_mov_id=21,par_id=31005,skill_kinds=0,skill_target=100,range_x=5,range_y=0,skill_damagetimer=5,skill_auto=1,},
[41001]={id=41001,name='灵蛇缠',des='灵蛇上棍，势如疾电。对目标造成基础（100%+技能等级*3）加固定伤害点（技能等级*4）的伤害。',limit_item=1,skill_type=1,is_hit=0,Initial_proc=0,range_type=0,range=0,distance=3,sing_time=0,cool_delay=1000,consumption_mp=1,consumption_item=0,consumption_num=0,need_lv=0,need_book=0,book_des='0',properties_add='attack',init_value=0,value_add=0,percentage_add=2,effect=0,probability_add=0,restraint_skill=0,value_less=0,percentage_less=0,probability_less=0,fear_skill=0,skill_add=0,skill_percentage_add=0,icon='Icon_sk_41001_1.png',gray_icon='Icon_sk_41001_0.png',atk_mov_id1=12,def_mov_id=21,par_id=41001,skill_kinds=0,skill_target=100,range_x=3,range_y=0,skill_damagetimer=2,skill_auto=1,},
[41002]={id=41002,name='寒星点',des='寒星粲然，利芒射月。对目标造成基础（100%+技能等级*2）加固定伤害点（技能等级*3）的伤害。',limit_item=1,skill_type=1,is_hit=0,Initial_proc=0,range_type=0,range=0,distance=10,sing_time=0,cool_delay=1000,consumption_mp=1,consumption_item=0,consumption_num=0,need_lv=0,need_book=0,book_des='0',properties_add='attack',init_value=0,value_add=0,percentage_add=2,effect=0,probability_add=0,restraint_skill=0,value_less=0,percentage_less=0,probability_less=0,fear_skill=0,skill_add=0,skill_percentage_add=0,icon='Icon_sk_41002_1.png',gray_icon='Icon_sk_41002_0.png',atk_mov_id1=12,def_mov_id=21,par_id=41002,skill_kinds=0,skill_target=100,range_x=6,range_y=0,skill_damagetimer=2,skill_auto=1,},
[41004]={id=41004,name='凤舞花',des='丹凤起舞，泼水难入。对目标造成基础（100%+技能等级*1.5）加固定伤害点（技能等级*2）的伤害。',limit_item=1,skill_type=1,is_hit=0,Initial_proc=0,range_type=1,range=0,distance=4.5,sing_time=0,cool_delay=1000,consumption_mp=1,consumption_item=0,consumption_num=0,need_lv=0,need_book=0,book_des='0',properties_add='attack',init_value=0,value_add=0,percentage_add=2,effect=0,probability_add=0,restraint_skill=0,value_less=0,percentage_less=0,probability_less=0,fear_skill=0,skill_add=0,skill_percentage_add=0,icon='Icon_sk_41004_1.png',gray_icon='Icon_sk_41004_0.png',atk_mov_id1=12,def_mov_id=21,par_id=41004,skill_kinds=0,skill_target=100,range_x=5,range_y=0,skill_damagetimer=4,skill_auto=1,},
[41005]={id=41005,name='狼烟扫',des='红妆铁衣，狼烟横扫。对目标造成基础（100%+技能等级*1.3）加固定伤害点（技能等级*2）的伤害。',limit_item=1,skill_type=1,is_hit=0,Initial_proc=0,range_type=2,range=0,distance=10,sing_time=0,cool_delay=1000,consumption_mp=1,consumption_item=0,consumption_num=0,need_lv=0,need_book=0,book_des='0',properties_add='attack',init_value=0,value_add=0,percentage_add=2,effect=0,probability_add=0,restraint_skill=0,value_less=0,percentage_less=0,probability_less=0,fear_skill=0,skill_add=0,skill_percentage_add=0,icon='Icon_sk_41005_1.png',gray_icon='Icon_sk_41005_0.png',atk_mov_id1=12,def_mov_id=21,par_id=41005,skill_kinds=0,skill_target=100,range_x=5,range_y=0,skill_damagetimer=4,skill_auto=1,},
[51001]={id=51001,name='雀啄',des='形拟雀落，勾镰剥啄。对目标造成基础（100%+技能等级*3）加固定伤害点（技能等级*4）的伤害。',limit_item=1,skill_type=1,is_hit=0,Initial_proc=0,range_type=0,range=0,distance=3,sing_time=0,cool_delay=1000,consumption_mp=1,consumption_item=0,consumption_num=0,need_lv=0,need_book=0,book_des='0',properties_add='attack',init_value=0,value_add=0,percentage_add=2,effect=0,probability_add=0,restraint_skill=0,value_less=0,percentage_less=0,probability_less=0,fear_skill=0,skill_add=0,skill_percentage_add=0,icon='Icon_sk_51001_1.png',gray_icon='Icon_sk_51001_0.png',atk_mov_id1=12,def_mov_id=21,par_id=51001,skill_kinds=0,skill_target=100,range_x=3,range_y=0,skill_damagetimer=2,skill_auto=1,},
[51002]={id=51002,name='雪爪',des='飞鹤踏雪，镰似爪利。对目标造成基础（100%+技能等级*2）加固定伤害点（技能等级*3）的伤害。',limit_item=1,skill_type=1,is_hit=0,Initial_proc=0,range_type=0,range=0,distance=10,sing_time=0,cool_delay=1000,consumption_mp=1,consumption_item=0,consumption_num=0,need_lv=0,need_book=0,book_des='0',properties_add='attack',init_value=0,value_add=0,percentage_add=2,effect=0,probability_add=0,restraint_skill=0,value_less=0,percentage_less=0,probability_less=0,fear_skill=0,skill_add=0,skill_percentage_add=0,icon='Icon_sk_51002_1.png',gray_icon='Icon_sk_51002_0.png',atk_mov_id1=12,def_mov_id=21,par_id=51002,skill_kinds=0,skill_target=100,range_x=6,range_y=0,skill_damagetimer=2,skill_auto=1,},
[51004]={id=51004,name='乱玉',des='镰光如雪，满地乱玉。对目标造成基础（100%+技能等级*1.5）加固定伤害点（技能等级*2）的伤害。',limit_item=1,skill_type=1,is_hit=0,Initial_proc=0,range_type=1,range=0,distance=4.5,sing_time=0,cool_delay=1000,consumption_mp=1,consumption_item=0,consumption_num=0,need_lv=0,need_book=0,book_des='0',properties_add='attack',init_value=0,value_add=0,percentage_add=2,effect=0,probability_add=0,restraint_skill=0,value_less=0,percentage_less=0,probability_less=0,fear_skill=0,skill_add=0,skill_percentage_add=0,icon='Icon_sk_51004_1.png',gray_icon='Icon_sk_51004_0.png',atk_mov_id1=12,def_mov_id=21,par_id=51004,skill_kinds=0,skill_target=100,range_x=5,range_y=0,skill_damagetimer=3,skill_auto=1,},
[51005]={id=51005,name='霜煞',des='霜风如刃，千锋袭人。对目标造成基础（100%+技能等级*1.3）加固定伤害点（技能等级*2）的伤害。',limit_item=1,skill_type=1,is_hit=0,Initial_proc=0,range_type=2,range=0,distance=10,sing_time=0,cool_delay=1000,consumption_mp=1,consumption_item=0,consumption_num=0,need_lv=0,need_book=0,book_des='0',properties_add='attack',init_value=0,value_add=0,percentage_add=2,effect=0,probability_add=0,restraint_skill=0,value_less=0,percentage_less=0,probability_less=0,fear_skill=0,skill_add=0,skill_percentage_add=0,icon='Icon_sk_51005_1.png',gray_icon='Icon_sk_51005_0.png',atk_mov_id1=12,def_mov_id=21,par_id=51005,skill_kinds=0,skill_target=100,range_x=5,range_y=0,skill_damagetimer=4,skill_auto=1,},
[10000]={id=10000,name='经脉冲穴',des='经脉冲穴',limit_item=0,skill_type=0,is_hit=1,Initial_proc=0,range_type=0,range=0,distance=0,sing_time=0,cool_delay=0,consumption_mp=1,consumption_item=0,consumption_num=0,need_lv=0,need_book=0,book_des='0',properties_add='0',init_value=0,value_add=0,percentage_add=0,effect=0,probability_add=0,restraint_skill=0,value_less=0,percentage_less=0,probability_less=0,fear_skill=0,skill_add=0,skill_percentage_add=0,icon='0',gray_icon='0',atk_mov_id1=12,def_mov_id=0,par_id=10000,skill_kinds=0,skill_target=100,range_x=10,range_y=5,skill_damagetimer=4,skill_auto=0,},
}
