--物品系统配置文件，客户端

_dofile (ClientConfigPath .. "Config/ItemConfig/ItemSystemEnum.lua")
_dofile (ClientConfigPath .. "Config/ItemConfig/ItemStoneConfig.lua")
_dofile (ClientConfigPath .. "Config/ItemConfig/ItemEquipConfig.lua")
_dofile (ClientConfigPath .. "Config/ItemConfig/ItemOtherConfig.lua")
_dofile (ClientConfigPath .. "Config/ItemConfig/ItemAmuletConfig.lua")
_dofile (ClientConfigPath .. "Config/ItemConfig/ItemEquipAppendConfig.lua")
_dofile (ClientConfigPath .. "Config/ItemConfig/ItemUIConfig.lua")
_dofile (ClientConfigPath .. "Config/ItemConfig/EquipPfx.lua")
_dofile (ClientConfigPath .. "Config/ItemConfig/ItemFightForbid.lua")
_dofile (ClientConfigPath .. "Config/ItemConfig/ItemPackUpFunc.lua")
_dofile (ClientConfigPath .. "Config/ItemConfig/ItemTreasureMapConfig.lua")
_dofile (ClientConfigPath .. "Config/ItemConfig/TreasureMapConfig.lua")
_dofile (ClientConfigPath .. "Config/ItemConfig/ItemSuitConfig.lua")
_dofile (ClientConfigPath .. "Config/ItemConfig/JingPoByQTotalNumAttrConfig.lua")
_dofile (ClientConfigPath .. "Config/ItemConfig/ItemFoundryConfig.lua")
_dofile (ClientConfigPath .. "Config/ItemConfig/ItemFrenzyHoeConfig.lua")
_dofile (ClientConfigPath .. "Config/ItemConfig/ItemAutoUesConfig.lua")
