dofile 'KernelService/LoginApp.lua'
dofile 'KernelService/PlayerInfoDefine.lua'
dofile 'KernelService/TransitManager.lua'
dofile 'KernelService/KernelService.lua'
dofile 'KernelService/PlayerService.lua'
dofile 'KernelService/HostService.lua'
dofile 'KernelService/AccountDBQuery.lua'
dofile 'KernelService/PlayerDBQuery.lua'
dofile 'KernelService/ShareDBQuery.lua'
dofile 'KernelService/Player.lua'
dofile 'KernelService/PlayerSystems.lua'
dofile 'KernelService/PlayerManager.lua'
dofile 'KernelService/LogoutGuard.lua'
dofile 'KernelService/KernelServiceMsg.lua'
dofile 'KernelService/GameLineManager.lua'
dofile 'KernelService/GameLine.lua' 
dofile 'KernelService/OfflineInfo/Project.lua'
dofile 'KernelService/PlayerShopSystem/Project.lua'
dofile 'KernelService/ChartManager/Project.lua'
dofile 'KernelService/GuildManager/Project.lua'
dofile 'KernelService/EvaluateManager/Project.lua'
--dofile 'KernelService/AvoidAddictedSystem/Project.lua' 
dofile 'KernelService/ChatManager/Project.lua' 
dofile 'KernelService/FriendSystem/Project.lua' 
dofile 'KernelService/MailSystem/Project.lua'
dofile 'KernelService/IncomeRecord/Project.lua'
dofile 'KernelService/AchievementManager/Project.lua'
dofile 'KernelService/DuplManager/Project.lua'
dofile 'KernelService/MarriageManager/Project.lua'
dofile 'KernelService/TianGuanCiFuMgr/Project.lua'
dofile 'KernelService/WarGame/Project.lua'
dofile 'KernelService/VipSystem/Project.lua'
dofile 'KernelService/PulseSystem/Project.lua'
dofile 'KernelService/MissionDailySystem/Project.lua'
dofile 'KernelService/RewardCodeSystem/Project.lua'
dofile 'KernelService/FiveElementSystem/Project.lua'
dofile 'KernelService/SeverEventSystem/Project.lua'
dofile 'KernelService/AllianceLeaderSystem/Project.lua'
dofile 'KernelService/ScriptSystem/Project.lua'
dofile 'KernelService/BackStageSystem/Project.lua'
dofile 'KernelService/LogSystem/Project.lua'

dofile 'KernelService/MergeServerTime/project.lua'

dofile 'KernelService/TimeRewardSystem/Project.lua'
dofile 'KernelService/BuildRampartManager/Project.lua'


dofile 'KernelService/LoginCall.lua'
dofile 'KernelService/LoginCall/Project.lua'
dofile 'KernelService/FestivalManager/Project.lua'

dofile 'KernelService/OnlineGiftMgr/Project.lua'
dofile 'KernelService/MuseSystem/Project.lua'
dofile 'KernelService/ExaminationManager.lua'

dofile 'KernelService/MallManager/Project.lua'

dofile 'KernelService/EquipBuildMgr/Project.lua'

dofile 'KernelService/FrenzyHoeSystem/Project.lua'
dofile 'KernelService/PracticeMgr/Project.lua'
dofile 'KernelService/LotterySystem/Project.lua'

dofile 'KernelService/EscortManager/Project.lua'
dofile 'KernelService/MegaKillMgr/Project.lua'
dofile 'KernelService/FullAwardSystem/Project.lua'
dofile 'KernelService/MatrixMethodSystem/Project.lua'
dofile 'KernelService/QihunMgr/Project.lua'

dofile 'KernelService/PetMgr/Project.lua'
dofile 'KernelService/ExpIntegrate/Project.lua'
dofile 'KernelService/CollectJewelSystem/Project.lua'
dofile 'KernelService/OnlineAwardsSystem/Project.lua'

dofile 'KernelService/ChallengeQunXiaSystem/Project.lua'

dofile 'KernelService/AddAttrMgr/Project.lua'
dofile 'KernelService/GourdSytem/Project.lua'

dofile 'KernelService/QunXiaLuSystem/Project.lua'

dofile 'KernelService/CrossSvrSystem/Project.lua'

dofile 'KernelService/DuGuSystem/Project.lua'

dofile 'KernelService/ChartAwardManager/Project.lua'
dofile 'KernelService/ZhenlongChessSystem/Project.lua'

dofile 'KernelService/ZhanQiJueSystem/Project.lua'
dofile 'KernelService/ShieldManager/Project.lua'
dofile 'KernelService/TongTianTowerManager/Project.lua'
dofile 'KernelService/TalkSwordManager/Project.lua'
dofile 'KernelService/RecyclingSystem/Project.lua'
