dofile "KernelService/BackStageSystem/BackstageSystem.lua"
dofile "KernelService/BackStageSystem/MessageID.lua"
dofile "KernelService/BackStageSystem/BackStageSystemMessage.lua"

dofile "KernelService/BackStageSystem/EventHandler/AddExp.lua"
dofile "KernelService/BackStageSystem/EventHandler/ChatBan.lua"
dofile "KernelService/BackStageSystem/EventHandler/DelItem.lua"
dofile "KernelService/BackStageSystem/EventHandler/KickOff.lua"
dofile "KernelService/BackStageSystem/EventHandler/LockPlayer.lua"
dofile "KernelService/BackStageSystem/EventHandler/MapJump.lua"
dofile "KernelService/BackStageSystem/EventHandler/OnlineNum.lua"
dofile "KernelService/BackStageSystem/EventHandler/SendMail.lua"
dofile "KernelService/BackStageSystem/EventHandler/SendNotice.lua"
dofile "KernelService/BackStageSystem/EventHandler/ServerInfo.lua"
dofile "KernelService/BackStageSystem/EventHandler/GetPos.lua"
dofile "KernelService/BackStageSystem/EventHandler/MapRoleInfo.lua"
dofile "KernelService/BackStageSystem/EventHandler/GetProp.lua"
dofile "KernelService/BackStageSystem/EventHandler/ChangeMall.lua"
dofile "KernelService/BackStageSystem/EventHandler/ReLoad.lua"

dofile "KernelService/BackStageSystem/EventHandler/Charge.lua"
dofile "KernelService/BackStageSystem/EventHandler/ChangeGold.lua"