--客户端配置文件加载
_dofile (ClientConfigPath .. 'Config/StrInfo.lua')
_dofile (ClientConfigPath .. 'Config/Locale.lua')
_dofile (ClientConfigPath .. 'Config/InitConfig.lua')
--_dofile (ClientConfigPath .. 'Config/RenderConfig.lua')
--_dofile (ClientConfigPath .. 'Config/SkipFontConfig.lua')
_dofile (ClientConfigPath .. 'Config/SkillDefine.lua')
_dofile (ClientConfigPath .. 'Config/ResRoleModelConfig.lua')
_dofile (ClientConfigPath .. 'Config/ResNpcModelConfig.lua')
_dofile (ClientConfigPath .. 'Config/MapConfig.lua')
_dofile (ClientConfigPath .. 'Config/ResPfxConfig.lua')
_dofile (ClientConfigPath .. 'Config/GameStateConfig.lua')
_dofile (ClientConfigPath .. 'Config/StringConfigInfo.lua')
_dofile (ClientConfigPath .. 'Config/ColorConfigInfo.lua')
_dofile (ClientConfigPath .. 'Config/NoticeIconConfig.lua')
_dofile (ClientConfigPath .. 'Config/NpcStringInfo.lua')
_dofile (ClientConfigPath .. 'Config/NPCTalkConfig.lua')
_dofile (ClientConfigPath .. 'Config/NpcLookConfig.lua')
_dofile (ClientConfigPath .. 'Config/SkillConfig/Project.lua')
_dofile (ClientConfigPath .. 'Config/ItemConfig/Project.lua')
_dofile (ClientConfigPath .. 'Config/ResPicConfig.lua')
_dofile (ClientConfigPath .. 'Config/NpcShopConfig.lua')
_dofile (ClientConfigPath .. 'Config/TradeConfig.lua')
_dofile (ClientConfigPath .. 'Config/StoneComposeConfig.lua')
_dofile (ClientConfigPath .. 'Config/EquipIntensifyConfig.lua')
_dofile (ClientConfigPath .. 'Config/PlayerShopConfig.lua')
_dofile (ClientConfigPath .. 'Config/MuseConfig.lua')
_dofile (ClientConfigPath .. 'Config/RoleUpLevelConfig.lua')
_dofile (ClientConfigPath .. 'Config/PulseConfig/Project.lua')
_dofile (ClientConfigPath .. 'Config/BournConfig.lua')
_dofile (ClientConfigPath .. 'Config/FiveElemConfig.lua')
_dofile (ClientConfigPath .. 'Config/FriendSystemConfig.lua')
_dofile (ClientConfigPath .. 'Config/GiftConfig.lua')
_dofile (ClientConfigPath .. 'Config/TaskConfig/TaskStateConfig.lua')
_dofile (ClientConfigPath .. 'Config/TaskConfig/TaskConfig.lua')
_dofile (ClientConfigPath .. 'Config/TaskConfig/TaskFun.lua')
_dofile (ClientConfigPath .. 'Config/TaskConfig/TaskChapterConfig.lua')
_dofile (ClientConfigPath .. 'Config/BuffSystemConfig/Project.lua')
--_dofile (ClientConfigPath .. 'Config/GameLineConfig.lua');
_dofile (ClientConfigPath .. 'Config/MarriageConfig.lua')
_dofile (ClientConfigPath .. 'Config/MallConfig.lua')
_dofile (ClientConfigPath .. 'Config/TeamConfig.lua')
_dofile (ClientConfigPath .. 'Config/ChatSystemConfig.lua')
_dofile (ClientConfigPath .. 'Config/VipConfig.lua')
_dofile (ClientConfigPath .. 'Config/NPCData.lua')

_dofile (ClientConfigPath .. 'Config/EventCenterConfig.lua')
_dofile (ClientConfigPath .. 'Config/TargetConfig.lua')
_dofile (ClientConfigPath .. 'Config/PanelPosConfig.lua')
_dofile (ClientConfigPath .. 'Config/SitConfig.lua')
_dofile (ClientConfigPath .. 'Config/CardConfig.lua')
_dofile (ClientConfigPath .. 'Config/NoviceGuideConfig.lua')
_dofile (ClientConfigPath .. 'Config/ChartConfig.lua')
_dofile (ClientConfigPath .. 'Config/EvaluateConfig.lua')
_dofile (ClientConfigPath .. 'Config/AchievementConfig/Project.lua')
_dofile (ClientConfigPath .. 'Config/GuildConfig.lua')
_dofile (ClientConfigPath .. 'Config/AuthorityConfig.lua')
_dofile (ClientConfigPath .. 'Config/ContinueKillConfig.lua')
_dofile (ClientConfigPath .. 'Config/DropFunctionConfig.lua')
_dofile (ClientConfigPath .. 'Config/LoginConfig.lua')
_dofile (ClientConfigPath .. 'Config/LoginDoohickeyConfig.lua')
_dofile (ClientConfigPath .. 'Config/LoginMsgConfig.lua')
_dofile (ClientConfigPath .. 'Config/LockRoundConfig.lua')
_dofile (ClientConfigPath .. 'Config/StoryConfig/StoryConfig.lua')
_dofile (ClientConfigPath .. 'Config/MountConfig/Project.lua')
_dofile (ClientConfigPath .. 'Config/MissionDailyConfig.lua')
_dofile (ClientConfigPath .. 'Config/SurNameConfig.lua')
_dofile (ClientConfigPath .. 'Config/WomanNameConfig.lua')
_dofile (ClientConfigPath .. 'Config/ManNameConfig.lua')
_dofile (ClientConfigPath .. 'Config/DuplConfig.lua')
_dofile (ClientConfigPath .. 'Config/AutoBattle/AutoBattleMsgConfig.lua')
_dofile (ClientConfigPath .. 'Config/AutoBattle/AutoBattleConfig.lua')
_dofile (ClientConfigPath .. 'Config/SkipNoticeConfig.lua')
_dofile (ClientConfigPath .. 'Config/MailSystemConfig.lua')

_dofile (ClientConfigPath .. 'Config/UIEffectConfig.lua')

_dofile (ClientConfigPath .. 'Config/AvoidAddictedConfig.lua')
_dofile (ClientConfigPath .. 'Config/DuplBasicConfig.lua')

_dofile (ClientConfigPath .. 'Config/MNLookConfig.lua')

_dofile (ClientConfigPath .. 'Config/SafeSideConfig.lua')
_dofile (ClientConfigPath .. 'Config/ExpPresentConfig.lua')
_dofile (ClientConfigPath .. 'Config/ResSfxConfig.lua')

_dofile (ClientConfigPath .. 'Config/FormulaConfig.lua')
_dofile (ClientConfigPath .. 'Config/ProjectSMovementConfig.lua')
_dofile (ClientConfigPath .. 'Config/SettingSystemConfig.lua')
_dofile (ClientConfigPath .. 'Config/MNSpeakConfig.lua')
_dofile (ClientConfigPath .. 'Config/AfterImgConfig.lua')
_dofile (ClientConfigPath .. 'Config/NotifyUseConfig.lua')
_dofile (ClientConfigPath .. 'Config/PotConfig.lua')
_dofile (ClientConfigPath .. 'Config/SortQueueConfig.lua')

_dofile (ClientConfigPath .. 'Config/MonsterConfig/MonsterDataConfig.lua')
_dofile (ClientConfigPath .. 'Config/MonsterConfig/MonsterFightInfo.lua')
_dofile (ClientConfigPath .. 'Config/MonsterConfig/MonsterAIInfo.lua')

_dofile (ClientConfigPath .. 'Config/GuildEscortConfig.lua')

_dofile (ClientConfigPath .. 'Config/SwordConfig/Project.lua')

_dofile (ClientConfigPath .. 'Config/GambleConfig/GambleConfig.lua')
_dofile (ClientConfigPath .. 'Config/CollectConfig/CollectConfig.lua')
_dofile (ClientConfigPath .. 'Config/TimeReward/TimeRewardConfig.lua')
_dofile (ClientConfigPath .. 'Config/ExchangeConfig.lua')
--_dofile (ClientConfigPath .. 'Config/Festival/Project.lua')
_dofile (ClientConfigPath .. 'Config/PKConfig.lua')






