dofile 'GameService/ChallengeQunXiaSystem/ChallengeQunXiaSystemMsg.lua'
dofile 'GameService/ChallengeQunXiaSystem/ChallengeQunXiaSystem.lua'
dofile 'GameService/ChallengeQunXiaSystem/ChallengeQunXiaSystemDB.lua'